- name: set locale
  shell: localectl set-locale LANG=ja_JP.utf8

- name: install google-chrome reoo
  template:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/
  when: browser == "google-chrome"

- name: install google-chrome
  yum:
    name: google-chrome-stable
    state: present
  when: browser == "google-chrome"

- name: install chromium
  yum:
    name:
      - chromium
      - http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
      - flash-player-ppapi
    enablerepo: epel
  when: browser == "chromium-browser"

- name: install flash player plugin
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: /usr/lib64/flash-plugin/libpepflashplayer.so
      dest: /usr/lib64/chromium-browser/PepperFlash/libpepflashplayer.so
    - src: /usr/lib64/flash-plugin/manifest.json
      dest: /usr/lib64/chromium-browser/PepperFlash/manifest.json

- name: install vncserver
  yum:
    name:
      - tigervnc-server
      - google-noto-cjk-fonts
    state: present
    enablerepo: epel

- name: ensure service user {{ worker_user }} exists
  user:
    name: "{{ worker_user }}"

- name: set vnc password
  shell: "echo -n {{ vnc_password }} | vncpasswd -f > /home/{{ worker_user }}/.vnc/passwd"
  become_user: "{{ worker_user }}"

- name: install systemd vncserver@:1.service
  template:
    src: vncserver.service.j2
    dest: /etc/systemd/system/vncserver@:1.service
  notify:
    - restart vncserver

- name: enable and start vncserver service
  systemd:
    name: vncserver@:1.service
    daemon_reload: yes
    enabled: yes
    state: started

- pip:
    name: websockify
    state: latest
    executable: pip3.4
  notify:
    - restart vnc-websock

- name: install systemd vnc-websock.service
  template:
    src: vnc-websock.service
    dest: /etc/systemd/system/vnc-websock.service
  notify:
    - restart vnc-websock

- name: enable and start vnc-websock.service
  systemd:
    name: vnc-websock.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: open port for websockify
  firewalld:
    port: "8901/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- name: install brozzler
  pip:
    name:
      - "{{ brozzler_pip_name }}"
      - youtube-dl
    state: latest
    executable: pip3.4
  notify:
    - restart brozzler-worker

- name: install systemd brozzler-worker.service
  template:
    src: brozzler-worker.service.j2
    dest: /etc/systemd/system/brozzler-worker.service
  notify:
    - restart vncserver

- name: enable and start brozzler-worker.service
  systemd:
    name: brozzler-worker.service
    daemon_reload: yes
    enabled: yes
    state: started
